name: Docker Workflow

on:
  workflow_dispatch:
  push:
    branches:
      - feature-branch-A
      - main

env: 
  MONGO_URI: "mongodb+srv://supercluster.d83jj.mongodb.net/superData"
  MONGO_USERNAME: ${{ vars.MONGO_USERNAME }}
  MONGO_PASSWORD: ${{ secrets.MONGO_PASSWORD }}

jobs:
  docker:
    name: containerization
    permissions:
      packages: write
      contents: read
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v5

      - name: Docker Hub Login
        uses: docker/login-action@v2
        with:
          username: ${{ vars.DOCKERUSERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build Docker image
        uses: docker/build-push-action@v3
        with:
          context: .
          push: false
          tags: |
            ${{ vars.DOCKERUSERNAME }}/solar-system:latest
            ${{ vars.DOCKERUSERNAME }}/solar-system:${{ github.sha }}

      - name: Test Docker image
        run: |
          docker images
          docker run --name solar-system-test -d \
            -p 3000:3000 \
            -e MONGO_URI=${{ env.MONGO_URI }} \
            -e MONGO_USERNAME=${{ env.MONGO_USERNAME }} \
            -e MONGO_PASSWORD=${{ env.MONGO_PASSWORD }} \
            ${{ vars.DOCKERUSERNAME }}/solar-system:${{ github.sha }}

          # Get container IP
          IP=$(docker inspect -f '{{range .NetworkSettings.Networks}}{{.IPAddress}}{{end}}' solar-system-test)
          echo "Container IP: $IP"

          # Test health endpoint
          echo "Testing Image URL..."
          curl -s http://127.0.0.1:3000/live | grep live
