name: Docker Workflow

on:
  workflow_dispatch:
  push:
    branches:
      - feature-branch-A
      - main

env: 
  MONGO_URI: "mongodb+srv://supercluster.d83jj.mongodb.net/superData"
  MONGO_USERNAME: ${{ vars.MONGO_USERNAME }}
  MONGO_PASSWORD: ${{ secrets.MONGO_PASSWORD }}

jobs:
  docker:
    name: containerization
    permissions:
      packages: write
      contents: read
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v5

      

      - name: ghcr Login
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ vars.GITHUB_USERNAME }}
          password: ${{ secrets.GITHUB_TOKEN }}

